jerseyClient:
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true
#  connectionRequestTimeout: 2000ms # Google API avg time to first byte is 1200 ms
#  connectionTimeout: 2000ms # Google API avg time to first byte is 1200 ms
  timeout: 2000ms
#This is just the configuration for logging
logging:
  level: INFO
  loggers:
    org.kramp.testservice: DEBUG
