resultsLimit: 5 # limits the upstream services results
timeout: 60 #The timeout of all of the request, i would prefer to have an nginx in fron of the app for this
jerseyClient:
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true
  timeout: 5000ms
#This is just the configuration for logging
logging:
  level: INFO
  loggers:
    org.kramp.testservice: DEBUG
